{% set name = "jupyterlab_email" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 112f3f481058f40c4656051e5e77b1963e8cd131db0366b403c6cfcb6e14f893

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

outputs:
  - name: jupyterlab_email
    requirements:
      host:
        - python >=3.7
        - pip
        - nodejs
        - yarn
        - jupyter-packaging
        - jupyterlab >=3.2.0
      run:
        - python >=3.7
        - beautifulsoup4 >=4.9.1
        - emails >=0.6
        - ipython
        - jupyterlab >=3.2.0
        - pandas >=0.23.4
      run_constrained:
        - {{ pin_subpackage("jupyterlab-email", max_pin="x.x.x") }}

    test:
      imports:
        - jupyterlab_email

  - name: jupyterlab-email
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("jupyterlab_email", max_pin="x.x.x") }}

    test:
      imports:
        - jupyterlab_email

about:
  home: http://github.com/timkpaine/jupyterlab_email
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Sending emails from JupyterLab

  description: |
    Sending emails from JupyterLab
  dev_url: https://github.com/timkpaine/jupyterlab_email

extra:
  recipe-maintainers:
    - timkpaine
